project:
  type: website
  output-dir: docs
  resources:
     - './presentations/*.pdf'

website:
  title: "Jaron Arbet, Ph.D."
  site-url: https://jarbet.github.io/
  description: "My personal website and blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: ./presentations
        text: Presentations
    right:
      - icon: github
        href: https://github.com/jarbet
      - icon: linkedin
        href: https://www.linkedin.com/in/jaron-arbet-6307b61b5/
      - icon: rss
        href: blog.xml

format:
  html:
    theme: materia
    toc: true

execute:
  freeze: auto
