name: Render site and open PR

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0'

permissions:
  contents: write
  pull-requests: write

jobs:
  render-and-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          quarto-version: 'latest'

      - name: Render website
        run: |
          quarto render --no-cache

      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: rebuild site (quarto render) - ${{ github.run_id }}"
          branch: "site-update-${{ github.run_id }}"
          title: "Rebuild site â€” ${{ github.run_number }}"
          base: main
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          paths: |
            docs/**
            listings.json
            search.json
          delete-branch: true
          skip-empty: true
          signoff: false
          assignees: jarbet
          reviewers: jarbet
          draft: false
          body: |
            Rebuild website
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
